name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up PowerShell
      uses: actions/setup-powershell@v2
    - name: Run PowerShell Script
      run: |
        Write-Host ""Hello, PowerShell CI!""
